import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'

export default function Home() {
  return (
    <div className='relative h-screen background bg-cover'>
      <Head>
        <title>Minecraft</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icon.webp" />
      </Head>

      {/* Minecraft Logo */}
      <div className='absolute top-20 left-10 right-10 sm:left-0 sm:right-0 flex items-center justify-center'>
        <Image src='/minecraft-logo.png' width='800' height='130' />
      </div>

      {/* Menu Buttons */}
      <Link href="/game">
        <div className='absolute top-[300px] left-10 right-10 sm:left-0 sm:right-0 flex items-center justify-center'>
          <button className='bg-[#848484] h-[60px] w-[550px] text-white text-2xl border border-black border-2 cursor-pointer'>Singleplayer</button>
        </div>
      </Link>
      <div className='absolute top-[370px] left-10 right-10 sm:left-0 sm:right-0 flex items-center justify-center'>
        <button className='bg-[#848484] h-[60px] w-[550px] text-white text-2xl border border-black border-2 cursor-pointer'>Multiplayer</button>
      </div>
      <div className='absolute top-[440px] left-10 right-10 sm:left-0 sm:right-0 flex items-center justify-center'>
        <button className='bg-[#848484] h-[60px] w-[550px] text-white text-2xl border border-black border-2 cursor-pointer'>Options</button>
      </div>

    </div>
  )
}
